export const defaultConfiguration = {
    white_start_time: "07:00",
    white_work_duration: "08:00",
    white_working_days_per_week: 5,
    white_is_penalty_given: true,
    white_late_time_tolerance: "00:15",
    white_late_salary_penalty_ph: 10000,
    white_late_salary_penalty_type: "Nominal",
    blue_is_penalty_given: false,
    blue_late_time_tolerance: "00:05",
    blue_late_salary_penalty_ph: 800,
    blue_late_salary_penalty_type: "Nominal",
}

export const defaultSalaryPercentage = {
    bpjs_kesehatan_type: "Percentage",
    bpjs_kesehatan_perusahaan: 4,
    bpjs_kesehatan_pribadi: 1,
    is_adding_bpjs_kesehatan: true,
    bpjs_ketenagakerjaan_jht_type: "Percentage",
    bpjs_ketenagakerjaan_jht_perusahaan: 3.7,
    bpjs_ketenagakerjaan_jht_pribadi: 1,
    is_adding_bpjs_ketenagakerjaan_jht: true,
    bpjs_ketenagakerjaan_jkk_type: "Percentage",
    bpjs_ketenagakerjaan_jkk_perusahaan: 0.24,
    is_adding_bpjs_ketenagakerjaan_jkk: false,
    bpjs_ketenagakerjaan_jkm_type: "Percentage",
    bpjs_ketenagakerjaan_jkm_perusahaan: 0.3,
    is_adding_bpjs_ketenagakerjaan_jkm: true,
    bpjs_ketenagakerjaan_jp_type: "Percentage",
    bpjs_ketenagakerjaan_jp_perusahaan: 2,
    bpjs_ketenagakerjaan_jp_pribadi: 1,
    is_adding_bpjs_ketenagakerjaan_jp: true,
}